/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cloud_logic_custom": [
        {
            "name": "notesapiauth",
            "endpoint": "https://kn03ddddae.execute-api.ap-south-1.amazonaws.com/test",
            "region": "ap-south-1"
        },
        {
            "name": "testapidemo",
            "endpoint": "https://burwst55f3.execute-api.ap-south-1.amazonaws.com/test",
            "region": "ap-south-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-south-1:b4ae2ff6-f72e-4c2b-af27-0f7ac4d1369c",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_oZVOwPQwc",
    "aws_user_pools_web_client_id": "1am8ak9sbabos1gg43297tio40",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
